#!/usr/bin/env python3
"""Train an AP residual ranker on honest crossfit dense-Prithvi features."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import torch

ROOT = Path(__file__).resolve().parents[1]
MODEL_ROOT = ROOT / "EarthRemoteSensingRapidResponse"
for path in (MODEL_ROOT, ROOT / "tools"):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from acquire_mars_metadata import sha256  # noqa: E402
from train_mars_dense_ap_residual_ranker import (  # noqa: E402
    evaluate_strength,
    fit_model,
    load_cache,
    load_exact_base_scores,
    predict_model,
    train_ensemble,
    write_json,
)


DEFAULT_PROTOCOL = Path(
    "configs/mars_dense_ap_honest_crossfit_ranker_protocol.json"
)


def validate_metadata_identity(
    honest: dict[str, np.ndarray],
    final: dict[str, np.ndarray],
) -> np.ndarray:
    final_row = {
        str(sample_id): index
        for index, sample_id in enumerate(final["sample_ids"].astype(str))
    }
    if len(final_row) != final["sample_ids"].size:
        raise ValueError("Final dense metadata repeats sample identifiers")
    matched_rows = np.empty(honest["sample_ids"].size, dtype=np.int64)
    for index, sample_id in enumerate(honest["sample_ids"].astype(str)):
        if sample_id not in final_row:
            raise ValueError(f"Honest crossfit sample is absent from final cache: {sample_id}")
        other = final_row[sample_id]
        matched_rows[index] = other
        for field in ("labels", "sensors", "groups", "folds"):
            if str(honest[field][index]) != str(final[field][other]):
                raise ValueError(
                    f"Honest and final dense metadata differ for {sample_id}: {field}"
                )
    return matched_rows


def train_cross_domain_ensemble(
    fit_features: np.ndarray,
    fit_labels: np.ndarray,
    fit_base_scores: np.ndarray,
    predict_features: np.ndarray,
    spec: dict[str, Any],
    seeds: list[int],
    device: torch.device,
) -> tuple[np.ndarray, list[dict[str, Any]], list[dict[str, Any]]]:
    fit_rows = np.arange(fit_features.shape[0], dtype=np.int64)
    predict_rows = np.arange(predict_features.shape[0], dtype=np.int64)
    predictions = []
    artifacts = []
    histories = []
    for seed in seeds:
        state, center, scale, history = fit_model(
            fit_features,
            fit_labels,
            fit_base_scores,
            fit_rows,
            spec,
            seed,
            device,
        )
        predictions.append(
            predict_model(
                predict_features,
                predict_rows,
                state,
                center,
                scale,
                spec,
                device,
            )
        )
        artifacts.append(
            {
                "seed": seed,
                "state": state,
                "center": center,
                "scale": scale,
            }
        )
        histories.append({"seed": seed, **history})
    return np.mean(predictions, axis=0), artifacts, histories


def write_markdown(path: Path, report: dict[str, Any]) -> None:
    selected = report["held"]["selected"]
    delta = selected["versus_current"]["delta"]
    interval = selected["paired_site_ap_delta"]
    lines = [
        "# Honest-crossfit dense AP residual ranker",
        "",
        "Development-only architecture evaluation. Every training feature was "
        "generated by an adapter that excluded the represented fold.",
        "",
        f"- Selected residual strength: {selected['strength']:.3f}",
        f"- Held-fold AP delta: {delta['average_precision']:+.6f}",
        f"- Held-fold matched-FPR recall delta: "
        f"{delta['recall_at_fpr_0_0713']:+.6f}",
        f"- Paired-site AP interval: "
        f"[{interval['lower']:+.6f}, {interval['upper']:+.6f}]",
        "",
        report["decision"],
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text("\n".join(lines), encoding="utf-8")
    os.replace(temporary, path)


def stratified_smoke_rows(
    folds: np.ndarray,
    labels: np.ndarray,
    sensors: np.ndarray,
    *,
    per_cell: int = 4,
) -> np.ndarray:
    selected = []
    for fold in np.unique(folds):
        for label in (0, 1):
            for sensor in (0, 1):
                rows = np.flatnonzero(
                    (folds == fold) & (labels == label) & (sensors == sensor)
                )
                if rows.size < per_cell:
                    raise ValueError(
                        f"Smoke cell fold={fold}, label={label}, sensor={sensor} "
                        f"has only {rows.size} rows"
                    )
                selected.extend(rows[:per_cell].tolist())
    return np.asarray(sorted(selected), dtype=np.int64)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--protocol", default=DEFAULT_PROTOCOL.as_posix())
    parser.add_argument("--internal-only", action="store_true")
    parser.add_argument("--smoke", action="store_true")
    args = parser.parse_args()
    if args.smoke and args.internal_only:
        raise ValueError("--smoke and --internal-only are mutually exclusive")
    protocol_path = (ROOT / args.protocol).resolve()
    protocol = json.loads(protocol_path.read_text(encoding="utf-8"))
    if sha256(Path(__file__).resolve()) != protocol["trainer"]["sha256"]:
        raise ValueError("Frozen honest-crossfit AP trainer hash mismatch")
    for dependency in protocol["code_dependencies"]:
        path = (ROOT / dependency["path"]).resolve()
        if sha256(path) != dependency["sha256"]:
            raise ValueError(f"Frozen dependency mismatch: {dependency['path']}")
    paths: dict[str, Path] = {}
    for name, contract in protocol["inputs"].items():
        path = (ROOT / contract["path"]).resolve()
        if sha256(path) != contract["sha256"]:
            raise ValueError(f"Frozen input mismatch: {name}")
        paths[name] = path

    honest_matrix, honest_metadata, honest_columns = load_cache(
        paths["honest_features"], paths["honest_metadata"]
    )
    final_matrix, final_metadata, final_columns = load_cache(
        paths["final_features"], paths["final_metadata"]
    )
    if not np.array_equal(
        honest_metadata["feature_names"], final_metadata["feature_names"]
    ) or not np.array_equal(honest_columns, final_columns):
        raise ValueError("Honest and final dense feature schemas differ")
    honest_rows_in_final = validate_metadata_identity(
        honest_metadata, final_metadata
    )
    honest_features = honest_matrix[:, honest_columns]
    honest_labels = honest_metadata["labels"].astype(np.uint8)
    honest_sensors = honest_metadata["sensors"].astype(np.uint8)
    honest_groups = honest_metadata["groups"].astype(str)
    honest_folds = honest_metadata["folds"].astype(np.uint8)
    honest_base = honest_metadata["exact_base_scores"].astype(np.float64)
    expected_folds = sorted(map(int, protocol["folds"]["fit"]))
    if sorted(map(int, np.unique(honest_folds))) != expected_folds:
        raise ValueError("Honest crossfit cache contains unexpected folds")
    if not np.allclose(
        honest_base,
        np.asarray(honest_features[:, 0], dtype=np.float64),
        atol=2.5e-4,
        rtol=5e-4,
    ):
        raise ValueError("Honest float16 score feature differs from its exact floor")
    final_base = load_exact_base_scores(paths["score_cache"], final_metadata)
    if not np.array_equal(honest_base, final_base[honest_rows_in_final]):
        raise ValueError("Honest exact score floor differs from the final cache contract")
    if not np.allclose(
        final_base,
        np.asarray(final_matrix[:, final_columns[0]], dtype=np.float64),
        atol=2.5e-4,
        rtol=5e-4,
    ):
        raise ValueError("Final float16 score feature differs from its exact floor")
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if device.type != "cuda":
        raise RuntimeError("Honest-crossfit AP ranker requires CUDA")
    spec = protocol["training"]
    if args.smoke:
        smoke_rows = stratified_smoke_rows(
            honest_folds,
            honest_labels,
            honest_sensors,
        )
        smoke_features = np.asarray(honest_features[smoke_rows])
        smoke_labels = honest_labels[smoke_rows]
        smoke_folds = honest_folds[smoke_rows]
        smoke_base = honest_base[smoke_rows]
        smoke_spec = {**spec, "steps": 2}
        internal_predictions = []
        for held in expected_folds:
            fit_rows = np.flatnonzero(smoke_folds != held)
            predict_rows = np.flatnonzero(smoke_folds == held)
            local, _artifacts, _histories = train_ensemble(
                smoke_features,
                smoke_labels,
                smoke_base,
                fit_rows,
                predict_rows,
                smoke_spec,
                [int(protocol["internal_seeds"][0]) + held * 100],
                device,
            )
            internal_predictions.append(local)
        final_smoke_features = np.asarray(
            final_matrix[:32][:, final_columns]
        )
        cross_domain, _artifacts, _histories = train_cross_domain_ensemble(
            smoke_features,
            smoke_labels,
            smoke_base,
            final_smoke_features,
            smoke_spec,
            [int(protocol["final_seeds"][0])],
            device,
        )
        internal = np.concatenate(internal_predictions)
        ok = bool(
            np.isfinite(internal).all()
            and np.isfinite(cross_domain).all()
            and internal.size == smoke_rows.size
            and cross_domain.size == final_smoke_features.shape[0]
        )
        print(
            json.dumps(
                {
                    "ok": ok,
                    "honest_rows": int(smoke_rows.size),
                    "fold_counts": {
                        str(int(fold)): int((smoke_folds == fold).sum())
                        for fold in np.unique(smoke_folds)
                    },
                    "internal_prediction_rows": int(internal.size),
                    "cross_domain_prediction_rows": int(cross_domain.size),
                    "feature_count": int(smoke_features.shape[1]),
                    "steps_per_model": int(smoke_spec["steps"]),
                }
            )
        )
        return 0 if ok else 1

    internal_rows = np.arange(honest_labels.size, dtype=np.int64)
    internal_residual = np.empty(internal_rows.size, dtype=np.float64)
    internal_histories: dict[str, Any] = {}
    for held in expected_folds:
        fit_rows = np.flatnonzero(honest_folds != held)
        predict_rows = np.flatnonzero(honest_folds == held)
        local, _artifacts, histories = train_ensemble(
            honest_features,
            honest_labels,
            honest_base,
            fit_rows,
            predict_rows,
            spec,
            [
                int(seed) + held * 100
                for seed in protocol["internal_seeds"]
            ],
            device,
        )
        internal_residual[predict_rows] = local
        internal_histories[str(held)] = histories
    if not np.isfinite(internal_residual).all():
        raise RuntimeError("Honest internal cross-fold residuals are incomplete")
    strengths = [float(value) for value in protocol["search"]["strengths"]]
    internal_candidates = [
        evaluate_strength(
            honest_labels,
            honest_sensors,
            honest_groups,
            honest_folds,
            honest_base,
            internal_residual,
            strength,
            protocol["bootstrap"],
            index,
            internal=True,
        )
        for index, strength in enumerate(strengths)
    ]
    internal_selected = max(internal_candidates, key=lambda row: tuple(row["rank"]))
    internal_report = {
        "rows": int(internal_rows.size),
        "folds": expected_folds,
        "histories": internal_histories,
        "candidates": internal_candidates,
        "selected": internal_selected,
    }
    if args.internal_only:
        print(
            json.dumps(
                {"ok": internal_selected["passed"], "internal": internal_report},
                indent=2,
            )
        )
        return 0 if internal_selected["passed"] else 2

    frozen_selection = protocol.get("frozen_internal_selection")
    if frozen_selection is None:
        raise ValueError("Held-fold evaluation requires a frozen internal selection")
    if (
        not internal_selected["passed"]
        or float(frozen_selection["strength"]) != float(internal_selected["strength"])
    ):
        raise ValueError("Recomputed honest internal selection differs from protocol")
    held_fold = int(protocol["folds"]["held"])
    held_rows = np.flatnonzero(final_metadata["folds"].astype(np.uint8) == held_fold)
    held_features = final_matrix[held_rows][:, final_columns]
    held_labels = final_metadata["labels"][held_rows].astype(np.uint8)
    held_sensors = final_metadata["sensors"][held_rows].astype(np.uint8)
    held_groups = final_metadata["groups"][held_rows].astype(str)
    held_folds = final_metadata["folds"][held_rows].astype(np.uint8)
    held_base = final_base[held_rows]
    final_residual, final_artifacts, final_histories = train_cross_domain_ensemble(
        honest_features,
        honest_labels,
        honest_base,
        held_features,
        spec,
        [int(seed) for seed in protocol["final_seeds"]],
        device,
    )
    held_selected = evaluate_strength(
        held_labels,
        held_sensors,
        held_groups,
        held_folds,
        held_base,
        final_residual,
        float(frozen_selection["strength"]),
        protocol["bootstrap"],
        100,
        internal=False,
    )
    passed = bool(held_selected["passed"])
    artifact = None
    if passed:
        artifact_path = (ROOT / protocol["outputs"]["artifact"]).resolve()
        if artifact_path.exists():
            raise FileExistsError(f"Refusing to overwrite artifact: {artifact_path}")
        artifact_path.parent.mkdir(parents=True, exist_ok=True)
        torch.save(
            {
                "schema_version": 1,
                "kind": "mars_dense_ap_honest_crossfit_ranker",
                "models": final_artifacts,
                "feature_columns": final_columns,
                "feature_names": final_metadata["feature_names"][final_columns],
                "residual_strength": float(frozen_selection["strength"]),
                "honest_feature_cache_sha256": sha256(paths["honest_features"]),
                "final_feature_cache_sha256": sha256(paths["final_features"]),
                "protocol_sha256": sha256(protocol_path),
            },
            artifact_path,
        )
        artifact = {
            "path": artifact_path.relative_to(ROOT).as_posix(),
            "bytes": artifact_path.stat().st_size,
            "sha256": sha256(artifact_path),
        }
    commit = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()
    report = {
        "schema_version": 1,
        "scope": "AP residual ranker on honest crossfit dense-Prithvi features",
        "all_promotion_gates_pass": passed,
        "decision": (
            "Authorize independent five-fold development cross-fitting."
            if passed
            else "Reject before five-fold cross-fit or exact-paper scoring."
        ),
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "provenance": {
            "git_commit": commit,
            "protocol_sha256": sha256(protocol_path),
            "trainer_sha256": sha256(Path(__file__).resolve()),
            "honest_features_sha256": sha256(paths["honest_features"]),
            "final_features_sha256": sha256(paths["final_features"]),
            "device": torch.cuda.get_device_name(0),
            "torch": torch.__version__,
            "numpy": np.__version__,
        },
        "input_features": int(final_columns.size),
        "excluded_feature": str(final_metadata["feature_names"][1]),
        "internal": internal_report,
        "held": {
            "fold": held_fold,
            "rows": int(held_rows.size),
            "histories": final_histories,
            "selected": held_selected,
        },
        "artifact": artifact,
        "external_inputs_accessed": False,
    }
    output_json = (ROOT / protocol["outputs"]["json"]).resolve()
    write_json(output_json, report)
    write_markdown((ROOT / protocol["outputs"]["markdown"]).resolve(), report)
    print(
        json.dumps(
            {
                "ok": passed,
                "strength": held_selected["strength"],
                "ap_delta": held_selected["versus_current"]["delta"][
                    "average_precision"
                ],
                "ap_lower": held_selected["paired_site_ap_delta"]["lower"],
                "recall_delta": held_selected["versus_current"]["delta"][
                    "recall_at_fpr_0_0713"
                ],
                "sensor_deltas": held_selected["versus_current"]["delta"][
                    "sensor_average_precision"
                ],
                "artifact": artifact,
            },
            indent=2,
        )
    )
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
